# Generated by Django 4.0 on 2023-08-19 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_friends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friends',
            name='users',
        ),
        migrations.AddField(
            model_name='friends',
            name='users',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.userbase'),
        ),
    ]
