# Generated by Django 4.0 on 2023-08-19 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_friends_users_friends_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friends',
            old_name='users',
            new_name='user',
        ),
    ]
