# Generated by Django 4.0 on 2023-08-19 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_rename_users_friends_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friends',
            old_name='user',
            new_name='friend_user',
        ),
    ]
