# Generated by Django 4.0 on 2023-08-19 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_rename_user_friends_friend_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friends',
            name='friend_user',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
