# Generated by Django 4.0 on 2023-08-19 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_friends_friend_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Friends',
        ),
    ]
