# Generated by Django 4.0 on 2023-08-22 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_delete_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbase',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
