# Generated by Django 4.0 on 2023-08-20 00:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0002_friends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friends',
            name='friend_user',
        ),
        migrations.AddField(
            model_name='friends',
            name='friend_user',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
