# Generated by Django 4.0 on 2023-08-20 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_delete_friends'),
        ('chat', '0003_remove_friends_friend_user_friends_friend_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='friends',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='User', to='account.userbase'),
        ),
    ]
