# Generated by Django 4.0 on 2023-08-20 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_delete_friends'),
        ('chat', '0004_friends_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friends',
            name='user',
        ),
        migrations.AddField(
            model_name='friends',
            name='from_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_ser', to='account.userbase'),
        ),
        migrations.AddField(
            model_name='friends',
            name='to_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to='account.userbase'),
        ),
    ]
