# Generated by Django 4.0 on 2023-08-20 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_delete_friends'),
        ('chat', '0005_remove_friends_user_friends_from_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friends',
            name='from_user',
        ),
        migrations.RemoveField(
            model_name='friends',
            name='to_user',
        ),
        migrations.AddField(
            model_name='friends',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='User', to='account.userbase'),
        ),
        migrations.CreateModel(
            name='Friend_Requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('from_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='friendships_sent', to='account.userbase')),
                ('to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='friendships_received', to='account.userbase')),
            ],
            options={
                'verbose_name': 'Friend Request',
                'verbose_name_plural': 'Friend Requests',
                'ordering': ('-created_date',),
            },
        ),
    ]
