# Generated by Django 4.0 on 2023-08-21 00:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0007_delete_friends'),
        ('chat', '0006_remove_friends_from_user_remove_friends_to_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friends',
            name='friend_user',
            field=models.ManyToManyField(blank=True, related_name='friend_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='BlockFriends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('blocked_fried', models.ManyToManyField(blank=True, related_name='blocked_friend', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='account.userbase')),
            ],
            options={
                'verbose_name': 'Blocked Friend',
                'verbose_name_plural': 'Blocked Friends',
                'ordering': ('-created_date',),
            },
        ),
    ]
