# Generated by Django 4.0 on 2023-08-21 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_alter_friends_friend_user_blockfriends'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blockfriends',
            options={'ordering': ('-created_date',), 'verbose_name': 'Block Friend', 'verbose_name_plural': 'Block Friends'},
        ),
    ]
