# Generated by Django 4.0 on 2023-08-21 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_alter_blockfriends_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlockFriends',
        ),
    ]
